name: bodega-proyect
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build --if-present
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy
        uses: hubertstefanski/action-railway@v1.1.4
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          railway_service: ${{ secrets.RAILWAY_SERVICE }}
